apiVersion: v2
name: cert-issuer
description: A Helm chart for Deploying and Configuring Cert Manager cluster issuer
type: application
version: 0.1.0
appVersion: 1.0.0
maintainers:
  - name: skyloud
    url: https://github.com/skyloud
  - name: a26p
    url: https://github.com/al26p

keywords:
- cert-manager
- cluster-issuer
- letsencrypt
