labels:
  "test": "true"

hosts:
  - url: test.url.local
    paths:
      - path: /test
        backend:
          serviceName: test-svc
          servicePort: 443
tls:
  - hosts:
      - test.url.local
    secretName: testsecret-tls
